php artisan cache:clear
php artisan config:cache
php artisan config:clear
php artisan route:cache
php artisan route:cache
php artisan clear:data
php artisan view:clear
php artisan optimize:clear
php artisan view:clear
php artisan serve